export const CACHE_ENTRY_ADDED = "CACHE_ENTRY_ADDED";
export const FETCH_EXECUTED = "FETCH_EXECUTED";
export const PARTIAL_COMPILED = "PARTIAL_COMPILED";
export const REQUEST_EXECUTED = "REQUEST_EXECUTED";
export const REQUEST_TIMED = "REQUEST_TIMED";
export const SCHEMA_TYPES_RECEIVED = "SCHEMA_TYPES_RECEIVED";
export const SUBSCRIPTION_EXECUTED = "SUBSCRIPTION_EXECUTED";
export const TYPE_CACHE_CONTROL_ADDED = "TYPE_CACHE_CONTROL_ADDED";
